# Generated by Django 4.2.2 on 2023-07-06 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaga_api', '0002_alter_vaga_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa', to='vaga_api.empresa'),
        ),
    ]
